#!/usr/bin/env python3
"""Experiment E1 comparison (Follow_Ups RAG-15): snapshot 694 (retrieval candidate count 200, reranking off) against
snapshot 598 (candidate count 40, reranking off).

Reads only the four committed JSON files named in FILES (paths relative to this script's directory) and writes the comparison
to stdout. Every value is labelled: "observed" values are read from a named file and field as stored; "derived" values are
computed by this script, with the computation stated. Numbers are parsed as written (Decimal), so stored values print unchanged.
It states where chunks sit and what changed; it states no cause.

Run: python3 compare_e1.py > comparison-694-vs-598.txt
"""
import json
import os
from decimal import ROUND_HALF_UP, Decimal

HERE = os.path.dirname(os.path.abspath(__file__))
REF = "../2026-09-13-evaluation-evidence/measurement/"
FILES = {
    "S598": REF + "snapshot-598-traced-snapshot-295-reference-rerank-off.json",
    "E598": REF + "evidence-598.json",
    "S694": "snapshot-694-candidate-count-200-rerank-off.json",
    "E694": "evidence-694.json",
}
RUNS = [("598", "S598", "E598"), ("694", "S694", "E694")]
TARGETS = [("nvda-02", 802), ("nvda-04", 754)]
METRICS = ["hit_at_1", "hit_at_3", "hit_at_5", "mrr"]
SLICE_METRICS = ["hitAt1", "hitAt3", "hitAt5", "mrr"]


def load(key):
    with open(os.path.join(HERE, FILES[key]), encoding="utf-8") as f:
        return json.load(f, parse_float=Decimal)


def fmt(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    return str(v)


def q6(d):
    return d.quantize(Decimal("0.000001"), rounding=ROUND_HALF_UP)


data = {k: load(k) for k in FILES}
out = []
p = out.append

p("E1 comparison: snapshot 694 (candidate count 200) against snapshot 598 (candidate count 40), both reranking off")
p("Generated by compare_e1.py from committed files only:")
for k, path in FILES.items():
    size = os.path.getsize(os.path.join(HERE, path))
    p(f"  {k} = {path} ({size} bytes)")
p("Labels: [observed: FILE field] a stored value read as written; [derived: computation] computed by this script.")
p("")

# 1. Identity and settings
p("1. Identity and settings")
for run, s, e in RUNS:
    S, E = data[s], data[e]
    p(f"  [observed: {s} id] {fmt(S['id'])}; [observed: {e} snapshotId] {fmt(E['snapshotId'])}; "
      f"[observed: {s} set_version, question_count, window_size, retrieval_strategy] "
      f"{S['set_version']}, {S['question_count']}, {S['window_size']}, {S['retrieval_strategy']}")
keys = []
for _, s, _ in RUNS:
    for k in data[s]["properties"]:
        if k not in keys:
            keys.append(k)
p("  [observed: S598 properties.<key> | S694 properties.<key>]; 'differs' is [derived: the two stored values are not equal]")
for k in keys:
    a = data["S598"]["properties"].get(k, "<absent>")
    b = data["S694"]["properties"].get(k, "<absent>")
    mark = "  differs" if a != b else ""
    p(f"    {k}: 598 {fmt(a)} | 694 {fmt(b)}{mark}")
for run, s, _ in RUNS:
    traces = data[s]["results"]["traces"]
    outcomes = {}
    for t in traces:
        o = t["trace"]["rerank"]["outcome"]
        outcomes[o] = outcomes.get(o, 0) + 1
    p(f"  [derived: count of results.traces in {s}, grouped by trace.rerank.outcome] {run}: {len(traces)} traces, "
      + ", ".join(f"{o} {n}" for o, n in sorted(outcomes.items())))
p("")


def trace_of(s, qid):
    return next(t["trace"] for t in data[s]["results"]["traces"] if t["id"] == qid)


def question_of(s, qid):
    return next(q for q in data[s]["results"]["questions"] if q["id"] == qid)


def evidence_question(e, qid):
    return next(q for q in data[e]["questions"] if q["id"] == qid)


# 2. Target chunks
p("2. nvda-02 (chunk 802) and nvda-04 (chunk 754)")
for qid, chunk in TARGETS:
    for run, s, e in RUNS:
        tr = trace_of(s, qid)
        q = question_of(s, qid)
        eq = evidence_question(e, qid)
        entry = next((f for f in tr["fused"] if f["chunkId"] == chunk), None)
        p(f"  {qid}, chunk {chunk}, snapshot {run}")
        p(f"    [observed: {s} results.traces[id={qid}].trace vectorCandidates, keywordCandidates, figureCandidates] "
          f"vector leg {fmt(tr['vectorCandidates'])}, keyword leg {fmt(tr['keywordCandidates'])}, figure leg {fmt(tr['figureCandidates'])}")
        p(f"    [derived: length of {s} results.traces[id={qid}].trace.fused] fused list {len(tr['fused'])}")
        vranks = sorted(f["vectorRank"] for f in tr["fused"] if f["vectorRank"] is not None)
        missing = [r for r in range(1, tr["vectorCandidates"] + 1) if r not in vranks]
        p(f"    [derived: trace.fused entries with a non-null vectorRank; values 1 to vectorCandidates not present among them] "
          f"{len(vranks)} entries, largest vectorRank {vranks[-1] if vranks else 'none'}, missing {missing if missing else 'none'}")
        if entry is None:
            p(f"    [derived: no element of trace.fused has chunkId {chunk}] chunk absent from the fused list")
        else:
            p(f"    [observed: {s} results.traces[id={qid}].trace.fused[chunkId={chunk}] vectorRank, keywordRank, figureRank, fusedPosition] "
              f"vectorRank {fmt(entry['vectorRank'])}, keywordRank {fmt(entry['keywordRank'])}, figureRank {fmt(entry['figureRank'])}, "
              f"fusedPosition {fmt(entry['fusedPosition'])}")
            if entry["vectorRank"] is None:
                p(f"    [derived: vectorRank null] chunk {chunk} absent from the vector leg ({fmt(tr['vectorCandidates'])} candidates)")
            else:
                p(f"    [derived: vectorRank compared with 40 and with the vector leg size] vector rank {entry['vectorRank']} is "
                  f"{'greater than 40 (outside' if entry['vectorRank'] > 40 else 'at most 40 (inside'} the first 40 vector candidates) "
                  f"and at most the vector leg size {tr['vectorCandidates']}")
        returned = tr["returnedChunkIds"]
        pos = returned.index(chunk) + 1 if chunk in returned else None
        p(f"    [observed: {s} results.traces[id={qid}].trace.returnedChunkIds] {returned}")
        p(f"    [derived: 1-based index of {chunk} in returnedChunkIds] "
          + (f"returned at position {pos}" if pos else f"not returned (not among the {len(returned)} returned chunks)"))
        p(f"    [observed: {s} results.questions[id={qid}] rank, matchedChunkId] rank {fmt(q['rank'])}, matchedChunkId {fmt(q['matchedChunkId'])}")
        holding = []
        for ph in eq["phrases"]:
            for c in ph["chunks"]:
                holding.append((ph["phrase"], c))
        p(f"    [observed: {e} questions[id={qid}].phrases[].chunks[].chunkId] chunks holding an accepted phrase: "
          + ", ".join(str(c["chunkId"]) for _, c in holding))
        for phrase, c in holding:
            if c["chunkId"] != chunk:
                continue
            ret = c.get("returnedPosition", {"value": "<field absent>", "basis": "-"})
            p(f"    [observed: {e} questions[id={qid}].phrases[].chunks[chunkId={chunk}] fusedPosition.value, rerankInput.value, "
              f"rerankedPosition.value, returnedPosition.value] {fmt(c['fusedPosition']['value'])}, {fmt(c['rerankInput']['value'])}, "
              f"{fmt(c['rerankedPosition']['value'])}, {fmt(ret['value'])} (bases {c['fusedPosition']['basis']}, "
              f"{c['rerankInput']['basis']}, {c['rerankedPosition']['basis']}, {ret['basis']})")
            agree_fused = entry is not None and c["fusedPosition"]["value"] == entry["fusedPosition"]
            agree_ret = ret["value"] == pos if ret["value"] != "<field absent>" else None
            p(f"    [derived: evidence fusedPosition equals trace fusedPosition; evidence returnedPosition equals the returnedChunkIds index] "
              f"fused {fmt(agree_fused)}, returned {fmt(agree_ret)}")
        p(f"    [observed: {e} questions[id={qid}] bestAcceptedChunk.value, bestAcceptedPosition.value, rerankOutcome.value] "
          f"{fmt(eq['bestAcceptedChunk']['value'])}, {fmt(eq['bestAcceptedPosition']['value'])}, {fmt(eq['rerankOutcome']['value'])}")
p("")

# 3. Leg sizes for every question
p("3. Leg sizes per question")
p("  columns: id, ticker [observed: S598 results.questions[].ticker]; for 598 then 694: vector, keyword, figure "
  "[observed: results.traces[id].trace vectorCandidates, keywordCandidates, figureCandidates]; fused [derived: length of trace.fused]")
p("  id        ticker | 598 vector keyword figure fused | 694 vector keyword figure fused")
for q in data["S598"]["results"]["questions"]:
    qid = q["id"]
    a, b = trace_of("S598", qid), trace_of("S694", qid)
    p(f"  {qid:<9} {q['ticker']:<6} | {fmt(a['vectorCandidates']):>10} {fmt(a['keywordCandidates']):>7} {fmt(a['figureCandidates']):>6} "
      f"{len(a['fused']):>5} | {fmt(b['vectorCandidates']):>10} {fmt(b['keywordCandidates']):>7} {fmt(b['figureCandidates']):>6} {len(b['fused']):>5}")
leg_diff = [q["id"] for q in data["S598"]["results"]["questions"]
            if any(trace_of("S598", q["id"])[k] != trace_of("S694", q["id"])[k] for k in ("keywordCandidates", "figureCandidates"))]
p(f"  [derived: questions whose keywordCandidates or figureCandidates differ between S598 and S694] {len(leg_diff)}: "
  f"{', '.join(leg_diff) if leg_diff else 'none'}")
sizes = {}
for q in data["S694"]["results"]["questions"]:
    sizes.setdefault(q["ticker"], set()).add(trace_of("S694", q["id"])["vectorCandidates"])
cc = data["S694"]["properties"]["candidateCount"]
p(f"  [derived: distinct S694 vectorCandidates values per ticker, each compared with S694 properties.candidateCount {cc}] "
  + "; ".join(f"{t} {sorted(v)} ({'less than' if max(v) < cc else 'equal to'} {cc})" for t, v in sorted(sizes.items())))
fused_lt = [q["id"] for q in data["S694"]["results"]["questions"]
            if len(trace_of("S694", q["id"])["fused"]) < trace_of("S694", q["id"])["vectorCandidates"]]
p(f"  [derived: S694 questions whose trace.fused length is less than trace.vectorCandidates] {len(fused_lt)}: {', '.join(fused_lt)}")
p("")

# 4. Rank and matched chunk per question
p("4. Rank and matched chunk per question")
p("  columns: rank, chunk [observed: S598 and S694 results.questions[id] rank, matchedChunkId]; "
  "differs [derived: rank or matchedChunkId not equal]; returned differs [derived: trace.returnedChunkIds lists not equal]")
p("  id        | 598 rank chunk | 694 rank chunk | differs | returned differs")
changed, returned_changed = [], []
ids598 = [q["id"] for q in data["S598"]["results"]["questions"]]
ids694 = [q["id"] for q in data["S694"]["results"]["questions"]]
for qid in ids598:
    a, b = question_of("S598", qid), question_of("S694", qid)
    d = (a["rank"], a["matchedChunkId"]) != (b["rank"], b["matchedChunkId"])
    rd = trace_of("S598", qid)["returnedChunkIds"] != trace_of("S694", qid)["returnedChunkIds"]
    if d:
        changed.append(qid)
    if rd:
        returned_changed.append(qid)
    p(f"  {qid:<9} | {fmt(a['rank']):>8} {fmt(a['matchedChunkId']):>5} | {fmt(b['rank']):>8} {fmt(b['matchedChunkId']):>5} | "
      f"{'yes' if d else 'no':>7} | {'yes' if rd else 'no'}")
p(f"  [derived: question id lists of S598 and S694 equal in order] {fmt(ids598 == ids694)} ({len(ids598)} questions)")
p(f"  [derived: questions whose rank or matchedChunkId differs] {len(changed)}: {', '.join(changed) if changed else 'none'}")
p(f"  [derived: questions whose returnedChunkIds differ] {len(returned_changed)}: {', '.join(returned_changed) if returned_changed else 'none'}")
for qid in sorted(set(changed) | set(returned_changed)):
    for run, s, _ in RUNS:
        q = question_of(s, qid)
        tr = trace_of(s, qid)
        m = q["matchedChunkId"]
        entry = next((f for f in tr["fused"] if f["chunkId"] == m), None) if m is not None else None
        p(f"    {qid} {run}: [observed: {s} results.questions[id={qid}] rank, matchedChunkId] {fmt(q['rank'])}, {fmt(m)}; "
          f"[observed: {s} results.traces[id={qid}].trace.returnedChunkIds] {tr['returnedChunkIds']}")
        if entry is not None:
            p(f"      [observed: {s} trace.fused[chunkId={m}] vectorRank, keywordRank, figureRank, fusedPosition] "
              f"{fmt(entry['vectorRank'])}, {fmt(entry['keywordRank'])}, {fmt(entry['figureRank'])}, {fmt(entry['fusedPosition'])}; "
              f"[observed: trace vectorCandidates, keywordCandidates, figureCandidates] {fmt(tr['vectorCandidates'])}, "
              f"{fmt(tr['keywordCandidates'])}, {fmt(tr['figureCandidates'])}")
p("")

# 5. Metrics
p("5. Metrics")
p("  columns: 598, 694 [observed: top-level field as stored]; 694 - 598 [derived: difference of the stored values]; "
  "recomputed [derived: from results.questions[].rank of the same file, hit@k = count(rank <= k) / question count, "
  "MRR = sum(1 / rank) / question count, at scale 6 half-up; 'equal' when it equals the stored value at scale 6]")


def recompute(s, metric):
    qs = data[s]["results"]["questions"]
    n = Decimal(len(qs))
    ranks = [q["rank"] for q in qs]
    if metric == "mrr":
        v = sum((Decimal(1) / Decimal(r) for r in ranks if r is not None), Decimal(0)) / n
    else:
        k = int(metric.rsplit("_", 1)[1])
        v = Decimal(sum(1 for r in ranks if r is not None and r <= k)) / n
    return q6(v)


for m in METRICS:
    a, b = data["S598"][m], data["S694"][m]
    ra, rb = recompute("S598", m), recompute("S694", m)
    p(f"  {m:<9} 598 {a} | 694 {b} | 694 - 598 {b - a} | recomputed 598 {ra} ({'equal' if ra == q6(a) else 'NOT equal'}), "
      f"694 {rb} ({'equal' if rb == q6(b) else 'NOT equal'})")
p("  per-ticker hit@5 [observed: results.tickerHitAt5.<TICKER>]; 694 - 598 [derived: difference]")
tickers = list(data["S598"]["results"]["tickerHitAt5"].keys())
for t in tickers:
    a = data["S598"]["results"]["tickerHitAt5"][t]
    b = data["S694"]["results"]["tickerHitAt5"].get(t)
    p(f"    {t}: 598 {a} | 694 {fmt(b)} | 694 - 598 {fmt(b - a if b is not None else None)}")
p("  slices [observed: results.slices.<slice>.<metric>, questionCount]; 694 - 598 [derived: difference]")
for sl in ["figure", "nonFigure"]:
    A, B = data["S598"]["results"]["slices"][sl], data["S694"]["results"]["slices"][sl]
    p(f"    {sl} (questions 598 {A['questionCount']}, 694 {B['questionCount']}): "
      + "; ".join(f"{m} 598 {A[m]} | 694 {B[m]} | diff {B[m] - A[m]}" for m in SLICE_METRICS))

print("\n".join(out))
