spring:
  application:
    name: SecKillSystem
  datasource:
    url: jdbc:mysql://localhost:3306/FlashSaleSystemDB?createDatabaseIfNotExist=true
    username: ${db_user}
    password: ${db_password}
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
