spring:
  application:
    name: RAGDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdemo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    user:
      name: ${DEV-USER-PW}
      password: ${DEV-USER-PW}

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  ingestion:
    enabled: false

  sec:
    filing-types:
      - 10-K
      - 10-Q
      - 8-K
    filings-per-type: 1
    base-url: "https://data.sec.gov"
    archive-base-url: "https://www.sec.gov"
    user-agent: ${USER-AGENT}
  secclient:
    stock-data-init: false


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-nano
    vectorstore:
      pgvector:
        initialize-schema: true

logging:
  level:
    org.apache.pdfbox.pdmodel.font.FileSystemFontProvider: error
    org.springframework.security: DEBUG