spring:
  application:
    name: StockRecommendationEngine

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:rag_db}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  ai:
    model:
      chat: none
      embedding: openai
      audio:
        speech: none
        transcription: none

    openai:
      api-key: ${OPENAI_API_KEY}

      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 1536


sec:
  user-agent: ${SEC_USER_AGENT}
  tickers-url: https://www.sec.gov/files/company_tickers.json
  submissions-base-url: https://data.sec.gov/submissions
  archives-base-url: https://www.sec.gov/Archives/edgar/data